// csv column types -> must match to server side
module.exports = [
    { id: 0, name: 'ת"ז', full_name: 'personal_identity', canEdit: false },
    { id: 30, name: 'קוד תושב', full_name: 'key', canEdit: false },
    { id: 1, name: 'שם פרטי', full_name: 'first_name', canEdit: false },
    { id: 2, name: 'טלפון', full_name: 'phone_number', canEdit: true },
    { id: 3, name: 'דואל', full_name: 'email', canEdit: true },
    { id: 4, name: 'סטטוס תמיכה סניף', full_name: 'support_status', canEdit: true },
    { id: 5, name: 'ספרדי', full_name: 'sephardi', canEdit: true },
    { id: 6, name: 'עיר', full_name: 'city', canEdit: true },
    { id: 7, name: 'רחוב', full_name: 'street', canEdit: true },
    { id: 8, name: 'בית', full_name: 'house', canEdit: true },
    { id: 9, name: 'שכונה', full_name: 'neighborhood', canEdit: true },
    { id: 10, name: 'כניסה', full_name: 'house_entry', canEdit: true },
    { id: 11, name: 'דירה', full_name: 'flat', canEdit: true },
    { id: 12, name: 'מיקוד', full_name: 'zip', canEdit: true },
    { id: 13, name: 'קוד מוסד', full_name: 'institute_id', canEdit: true },
    { id: 14, name: 'קוד תפקיד במוסד', full_name: 'institute_role_id', canEdit: true },
    { id: 15, name: 'קוד רמת סיווג', full_name: 'classification_id', canEdit: true },
    { id: 16, name: 'הצביע', full_name: 'voted', canEdit: true },
    { id: 17, name: 'שם משפחה', full_name: 'last_name', canEdit: false },
    { id: 18, name: 'נפטר כן/לא', full_name: 'deceased', canEdit: true },
    { id: 19, name: 'תאריך פטירה', full_name: 'deceased_date', canEdit: true },
    { id: 20, name: 'תאריך לידה', full_name: 'birth_date', canEdit: true },
    { id: 21, name: 'סטטוס תמיכה סופי', full_name: 'support_status_final', canEdit: true },
    { id: 22, name: 'שעת הצבעה', full_name: 'vote_time', canEdit: true },
    { id: 23, name: 'עדה', full_name: 'ethnic_group_id', canEdit: true },
    { id: 24, name: 'מגדר', full_name: 'gender', canEdit: true },
    //{ id: 25, name: 'חרדי', full_name: 'strictly_orthodox', canEdit: true },
	{ id: 26, name: 'הסעה', full_name: 'transportation_type', canEdit: true },
    { id: 27, name: 'הסעה משעה', full_name: 'transportation_from_time', canEdit: true },
    { id: 28, name: 'הסעה עד שעה', full_name: 'transportation_to_time', canEdit: true },
    { id: 29, name: 'זרם', full_name: 'religious_group_id', canEdit: true },
];