---
version: 2.1
jobs:
  build-and-deploy:
    steps:
      - checkout
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r test_dir/requirements.txt
      - save_cache:
          key: deps1-{{ checksum "test_dir" }}
          paths:
            - "test_dir"


workflows:
  version: 2
  build:
    jobs:
      - deploy:
          filters:
            branches:
              only: main 

# only deploy on the main branch
# ssh $SSH_USER@$SSH_HOST "ansible dev -m command -a 'hostname'"
# - run: ssh $SSH_USER@$SSH_HOST "ansible-playbook /home/ubuntu/ansible/playbook.yaml"
# - run: ssh $SSH_USER@$SSH_HOST "ansible dev -i /home/ubuntu/ansible/inventory -m file -a 'path=/home/ubuntu/ubuntu_test.txt state=touch'"
#- run: ssh $SSH_USER@$SSH_HOST "ansible all -i inventory -m ping"


# ---
# version: 2.1
# jobs:
#   deploy:
#     machine:
#       image: ubuntu-2004:202111-02
#     resource_class: medium
#     working_directory: ~/shass_app
#     steps:
#       - checkout
#       - run:
#           name: ls test_dir
#           command: |
#              ls test_dir
#       - restore_cache:
#         keys:
#           - test_dir-key-{{ checksum "test_dir-key" }}
#       - run:
#           name: ls test_dir
#           command: |
#              ls test_dir
#       - save_cache:
#           key: test_dir-key
#           paths:
#             - test_dir   