<?php

namespace App\Enums;

abstract class GeographicEntityType
{
    const GEOGRAPHIC_ENTITY_TYPE_AREA_GROUP = -1;
    const GEOGRAPHIC_ENTITY_TYPE_AREA = 0;
    const GEOGRAPHIC_ENTITY_TYPE_CITY = 1;
    const GEOGRAPHIC_ENTITY_TYPE_NEIGHBORHOOD = 2;
    const GEOGRAPHIC_ENTITY_TYPE_CLUSTER = 3;
    const GEOGRAPHIC_ENTITY_TYPE_BALLOT_BOX = 4;
    const GEOGRAPHIC_ENTITY_TYPE_SUB_AREA = 5;
    const GEOGRAPHIC_ENTITY_TYPE_QUARTER = 6;
    const GEOGRAPHIC_ENTITY_TYPE_CAPTAIN_100 = 100;
}
